### ISSUE TITLE
Mac m1 Support

### ISSUE THREAD

**Issue by MustCodeAl** [sidkshatriya/rd#17]
is it possible to use this software tool on the m1 mac?

**Comment by sidkshatriya** [comment]
No it is not possible currently for rd to work on M1.

It would require a lot of work to make rd support M1 (Linux). First we would need to add AArch64 support which rd lacks (rr supports AArch64 BTW).

Recently rr master branch received changes to allow it to work on Mac M1 (Asahi Linux) so you may want to check that out!

See https://github.com/rr-debugger/rr/pull/3144
